name: sciencelive
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - altair
  - nbqa
  - ruff
  - black
  - isort
  - nbconvert
  - pytest
  - pytest-cov
  - jupyter
  - mystmd
  - nodejs=18  # For mystmd CLI
